/*
Deployment script for C:\USERS\JITIN\DOCUMENTS\GITHUB\4870\MARYPIZZERIA\APP_DATA\MARYPIZZA.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\JITIN\DOCUMENTS\GITHUB\4870\MARYPIZZERIA\APP_DATA\MARYPIZZA.MDF"
:setvar DefaultFilePrefix "C_\USERS\JITIN\DOCUMENTS\GITHUB\4870\MARYPIZZERIA\APP_DATA\MARYPIZZA.MDF_"
:setvar DefaultDataPath "C:\Users\Jitin\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"
:setvar DefaultLogPath "C:\Users\Jitin\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[Table]...';


GO
CREATE TABLE [dbo].[Orders] (
    [Id]             INT           NOT NULL,
    [First Name]     VARCHAR (20)  NOT NULL,
    [Last Name]      VARCHAR (20)  NOT NULL,
    [Email]          VARCHAR (50)  NOT NULL,
    [Telephone]      VARCHAR (10)  NOT NULL,
    [Pizza Size]     CHAR (2)      NOT NULL,
    [Pizza Quantity] NUMERIC (18)  NOT NULL,
    [Toppings]       VARCHAR (256) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
